docs/documentation/documentation.html

Super basic documentation so that users can at least get Manon up and running locally to play around with it.

Add simple docs explaining how Manon can be installed to read the documentation.

---

docs/documentation/components/max-line-length.html

fix: Removed redundant link within max-line-length.html. As max-line-length is currently in use on all the docs pages it's no longer necessary to specify it on the max-line-length page.

fix: Removed redundant link

---

docs/documentation/components/max-line-length.html

fix: table cells html use td instead of th where needed.

fix: table cells html

---

docs/documentation/components/article.html
docs/documentation/components/layout-base.html
docs/documentation/components/section.html
manon/article-variables.scss
manon/article.scss
manon/layout-base-variables.scss
manon/section-variables.scss
manon/section.scss

- Changed section, article and base title margin to match with headings styling
BREAKING: 
Article
Removed: --article-title-margin-top
Removed: --article-title-margin-bottom 
Use instead: --article-title-margin
Section
Removed:--section-title-margin-top
Removed:--section-title-margin-bottom 
Use instead: --section-title-margin
Layout base
Removed:--layout-base-content-block-title-margin-top
Removed:--layout-base-content-block-title-margin-bottom 
Use instead:--layout-base-content-block-title-margin

fix: section, article and base title margin

---

docs/documentation/components/form-horizontal-view-test.html
manon/form-horizontal-view-fieldset-variables.scss
manon/form-horizontal-view-fieldset.scss
manon/form-horizontal-view-variables.scss
manon/form-horizontal-view.scss

- fix: Wrapping issue on horizontally aligned forms.
- fix: Button alignment within horizontally aligned forms.
**Testing:** 
For default state (including flexbox): 
file:///Users/buppp/Projecten/Colorful_media/Projecten/brba/91divoc-ln/nl-rdo-manon/docs/documentation/components/form-horizontal-view-test.html#input
For fieldsets:
file:///Users/buppp/Projecten/Colorful_media/Projecten/brba/91divoc-ln/nl-rdo-manon/docs/documentation/components/form-horizontal-view-test.html#fieldset

fix: form horizontal view alignment issues

---

manon/form-help.scss

fix: Form help alignment.
The new layout introduced unwanted padding within this element resulting in alignment issues. This pr solves that issue.
Before: 
After:

fix: Form help alignment.

---

manon/form-horizontal-view-fieldset.scss

fix: fieldset checkbox alignment horizontal view. Align correctly with elements outside the fieldset.

fix: fieldset checkbox alignment horizontal view. 

---

manon/focus-only.scss

Currently the button to go the content adds white space on top of the page.
```
<a href="#main-content" class="button focus-only">Ga direct naar inhoud</a>
```
This PR sets the border to 0 and that removed the whitespace on top of the page.

fix: set border to 0 on focus-only class

---

docs/scss/themes/soft/body-text-set.scss
docs/scss/themes/soft/header-navigation.scss
manon/breadcrumb-bar-variables.scss
manon/breadcrumb-bar.scss
manon/header-navigation-variables.scss
manon/header-navigation.scss
manon/link-variables.scss
manon/navigation-collapsible-menu.scss

Updated nav styling options and fixed issues found. Added manon docs nav styling.
fix: unexpected behaviour (visited links styling) 
added: Styling options. E.g border-styles and min-height on items.
updated: docs main nav styling
Solves: https://github.com/minvws/nl-rdo-manon/issues/119
Before: 
After:

Update nav styling

---

manon/link.scss
manon/max-line-length-variables.scss

Removed white-space:break-spaces as it was resulting in undesirable behaviour in combination with linters.

Fix: Unnecessary white space within links

---

docs/documentation/components/hidden.html
manon/hidden.scss
manon/notification-paragraph.scss

Having an element like:
`<p class="error" role="status" hidden></p>`
Renders:
The current `display: inline-block;` overwrites the browser hidden `display: none;`. With this change the hidden styling is used when an element has the hidden attribute.

Hide elements with hidden attribute

---

manon/navigation.js

Fix: removed broken hidden attribute. The state added to the hidden attribute is non-existing so it referred back to its default state which is "hidden". I removed the addition of the hidden attribute since it was redundant as the css hides the button when needed.

Fix: removed broken hidden attribute

---

manon/footer-variables.scss
manon/footer.scss

fix: link styling including states and before's 
Solves the issue where links were the expected color. But before and states like visited links were not.

fix: link styling including before and states

---

.github/workflows/npm-publish.yml

npm is limited to one registry per scope. 
When using a @minvws scoped private npm package hosted on GitHub npm registry, npm could not find this package on the GitHub npm registry. With this fix we will also publish the package to this registry.
There is a RFC at npm for this: https://github.com/npm/rfcs/issues/275 and https://github.com/npm/statusboard/issues/340.

Publish as package on GitHub packages

---

manon/image-cover.scss
manon/image-round.scss
manon/image-square.scss

- Fixes height on square and round images
Padding inherited from layout elements pushed the square images to be too long. This pr solves this issue.

Fixes height on square and round images

---

manon/form-help-button-centered-variables.scss
manon/form-help-variables.scss
manon/form-help.js
manon/form-help.scss

Based on aria-expanded set the expanded content.
Not expended:
Expended:
After removing icon classes the help-button missed `gap: 0`.  So added that.

Removed icon classes from help button and use css

---

manon/sidemenu.js

It is possible to set the open and close buttons with css variables.
See:
https://github.com/minvws/nl-rdo-manon/blob/89b802488c53a1361cf2c753cb43118430e6a8ca/manon/sidemenu-base-variables.scss#L61-L65

Remove icon open and icon close classes in sidemenu js

---

manon/form-textarea-variables.scss

Updated form-textarea-variables to use the form-input-variables for background-color, text-color and border.
Do we need to set default for input?
https://github.com/minvws/nl-rdo-manon/blob/b715090c9d05c31f10673125493099b30719a1f2/manon/form-input-variables.scss#L5-L18

Set form textarea styling based on form input styling

---

docs/documentation/components/css/link-variables.css
docs/documentation/components/link.html
docs/scss/manon.scss
manon/link-external-variables.scss
manon/link-external.scss
manon/link.scss

With this it is possible to set an icon for an external link.
```css
--link-external-icon: var(--icon-cat)
```
Example link:
```html
<a href="#" rel="external">Externe link</a>
```

External link icon

---

docs/documentation/components/form-horizontal-view-test.html
manon/form-horizontal-view-fieldset.scss
manon/form-horizontal-view.scss

Fix: Incosistent classname for radio buttons
Breaking change: class="radio-button" is now class="radio"

Fix: Inconsistent classname for radio buttons

---

manon/description-list-variables.scss
manon/description-list.scss

- Fixed broken variables
- Styling fixes (Layout, styling options.)
- 
Before:
After:

Fix: dl styling and fixed broken variables

---

docs/documentation/components/form-horizontal-view-test.html
manon/button-base-variables.scss
manon/form-horizontal-view.scss

Fix: Fixes horizontal form button container alignment
For test see: form-horizontal-view-test.html
Current: 
After:

Fix: Fixes horizontal form button container alignment

---

manon/header-navigation-link-focus.scss
manon/header-navigation-link-hover.scss

The `ul, ol li selector was outside the nav element. This _ofcourse_ caused problems with other items like the language selector.

Fix header navigation link to be applied on links within nav

---

manon/sidemenu-variables.scss
manon/sidemenu.scss

Sets the default sidemenu content container padding to 0.
Removed `--sidemenu-content-container-background-color`.

Update sidemenu content-container

---

manon/sidemenu-variables.scss
manon/sidemenu.scss

It overriden the default article, div and section padding, thats why it is removed.
Now it is possible to set a background color on an article and the color will be full width.

Remove sidemenu content container padding

---

manon/mixins/collapsible.scss

Now we have text on the collapsible-toggle the 0 padding is not reasonable anymore. By removing this is uses the default button padding.
If we need custom padding for the collapsible-toggle, we can add that in the future.

Fix: Removed 0 padding from collapsible-toggle

---

.github/dependabot.yml

Since june it is possible to keep pnpm dependencies up to date with Dependabot.
https://github.blog/changelog/2023-06-12-dependabot-version-updates-now-supports-pnpm/

Add pnpm to dependabot

---

manon/accordion-variables.scss
manon/accordion.scss
manon/button-base.scss

Chose to use display flex on wider screens as the known issues with flexbox only occur on smaller screens. 
- Fixes button alignment on wider screens
- Fixes accordion button alignment
- Fills in empty variables on accordion.
Solves: 
https://github.com/minvws/nl-rdo-manon/issues/368

Fixes alignment issues with buttons on wider screens

---

manon/visually-hidden.scss

This is an attempt at addressing an issue with `.visually-hidden`, using VoiceOver (Safari 16.6, macOS 13.5).
The `width: 0`, `height: 0`, `max-width: 0` and `max-height: 0` cause VoiceOver not to read `.visually-hidden` elements in some contexts, including table `<caption>`s.
Omitting the `max-width` and `max-height` and setting `width` and `height` to `1px` seems to address this issue without anything becoming visible.
This requires further testing.

fix: .visually-hidden (VoiceOver on macOS)

---

manon/button-base-variables.scss

This PR adds default values for all the `--button-base-*-border-style` and `--button-base-*-border-width` vars. These vars being undefined resulted in the `:active`, `:focus` and `:selected` button states getting the equivalent of `border-style: unset`, which causes unexpected behaviour on buttons, leaving them without a border, even if `border-width` is set later.

fix: button border-style

---

docs/documentation/components/table-expando-row.html
manon/table-expando-rows-variables.scss
manon/table-expando-rows.scss

Removes header styling options from expando rows as that behaviour is now covered by headings-base-set. And setting the variables within the element will block the usage of the classes as set up in headings-set.

Removes header styling options from expando rows 

---

manon/header-navigation-button-states.scss

Links can have visited styling. For a link that we display as a button there was not visited styling configured.
This adds this adds the visited styling to be displayed.
Because button does not have a visited state this configures the styling to use the default button styling.

chore(navigation-link-button): added visited state styling for the navigation link button

---

docs/documentation/components/filter.html

This PR updates the Filter documentation to add instructions to give the `<form>` an accessible name. This way it is presented as a named group to assistive technology users.

fix: filter form accessible group name

---

manon/filters.js

This PR changes which element forms.js uses as the `aria-controls` target. Instead of the grandparent of the button (`.filter`), it now targets the actual `form` that the button controls.

fix: filters.js aria-controls target

---

.github/workflows/npm-publish.yml

Based on the github tag the npm tag is added.
For example if we release [v16.3.0-beta.2](https://github.com/minvws/nl-rdo-manon/releases/tag/v16.3.0-beta.2) the npm tag `beta` is set.
If we release [v16.2.0](https://github.com/minvws/nl-rdo-manon/releases/tag/v16.2.0) the npm tag `latest` is set.

chore(add-npm-tag): add npm tags to releases

---

pnpm-lock.yaml
themes/package.json

Fix @minvws/manon-themes peer dependencies, which were not working due to silly typos from #442.
https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt 
and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

fix: manon-themes peerDependencies

---

examples/laravel-mix/main.scss

Fix the `$font-path` variable name in the theme import in the laravel-mix example.

fix: laravel-mix example

---

docs/package.json
docs/svelte.config.js
examples/laravel-mix/main.scss
examples/laravel-mix/package.json
examples/sass-cli/package.json
examples/vite/package.json
manon/package.json
package.json
pnpm-lock.yaml

Update various dependencies, including  sass to `1.69.7`, sveltekit to `2.3.2` and vite to `5.0.11`.

chore: update dependencies

---

pnpm-lock.yaml

Update `example/laravel-mix`'s nested depencies. Resolves the audit warning (e.g. on [#491](https://github.com/minvws/nl-rdo-manon/pull/491)'s [CI job 22772557435](https://github.com/minvws/nl-rdo-manon/actions/runs/8323263815/job/22772557435?pr=491)).

chore: update laravel-mix dependencies

---

pnpm-lock.yaml

Update the nested dependencies to resolve the npm audit failure (see [this CI run](https://github.com/minvws/nl-rdo-manon/actions/runs/8422498185/job/23061917619)) caused by a vuln in webpack-dev-middleware, a nested dependency of [./examples/laravel-mix](./examples/laravel-mix).

chore: update nested dependencies

---

.github/actions/setup/action.yml
.github/workflows/publish.yml

Fix the CI regression from #511, which inadvertantly removed the `registry-url` from the publish jobs.

fix: npm publish registry-url

---

manon/sidemenu.scss

This reverts a small part of PR #402 (commit e431f41), which inadvertantly introduced a breaking change.

revert: sidemenu-list-item text styles

---

docs/src/routes/(docs)/components/message-counter/+page.svelte

This PR updates the `message-counter` docs to remove the instruction to add an `aria-label`. Instead, the docs now give the advice to ensure _surrounding_ elements have appropriate labels.
There is a case to be made to try and improve reading order in some cases. E.g. in some contexts, when a link has the text "messages" followed by a message counter, it could make sense for the accessible name of the link to be "42 messages" instead of "messages 42". We could consider adding an example of how to accomplish this e.g. using `aria-label` on the enclosing interactive element and using `aria-hidden` on the content elements. But I feel like that might be outside of the scope of the `message-counter` docs.
Fixes #417

docs: message counter accessibility

---

docs/src/routes/+layout.js

This PR fixes a CI build regression introduced in #535. The prerendered redirects didn't take into account the optional `BASE_PATH` which we use for the github pages build, causing build failures (see e.g. [this run](https://github.com/minvws/nl-rdo-manon/actions/runs/9060539218/job/24912795385)).

ci: fix github pages docs redirects (apply BASE_PATH)

---

docs/src/routes/(docs)/components/table-checkbox-test/+page.svelte
docs/src/routes/(docs)/components/table-checkbox/+page.svelte

This PR updates the docs regarding checkboxes in tables to ensure WCAG SC 1.3.1 and 4.1.2 are met and adds a (very) simple JS example implementation for the "select all" behaviour.
Screenreader demo (NVDA 2024.1, FireFox 125.0.3):
Closes #416

docs: table checkbox accessibility

---

themes/basic-bold/components/header-content-wrapper.scss

Fixes wrapping behaviour of header-content-wrapper within basic-bold theme

fix: Header wrapping behaviour basic bold theme

---

manon/accordion.js

These changes should close #444  for pages that by accident mess up their accordion code

Update accordion.js, closes #444

---

themes/icore-open/fonts/fonts.scss

This PR fixes the icore-open theme's `@font-face` rules.
The regular [`font-family` property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) takes a list of fonts, but the `@font-face`'s [`font-family` descriptor](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-family) only takes the font's name. Adding a `sans-serif` "fallback" causes issues.

fix: icore-open font-faces

---

icore_open_docs/src/routes/(docs)/components/notification-explanation/+page.svelte
icore_open_docs/src/routes/(docs)/components/table-base/+page.svelte

Currently the svelte build for icore docs crashes because the href targets were not found.
This removes the href links and the docs can be build again.

Fix links svelte icore docs

---

docs/src/lib/Code.svelte
icore_open_docs/src/lib/Code.svelte

This PR fixes the issue where some code blocks were rendered incorrectly due to unescaped comments in the commented plaintext version of the highlighted Code blocks.
As reported by @ricklambrechts:

fix: remove source code comment from docs Code component

---

docs/src/lib/BreadcrumbNav.svelte
icore_open_docs/src/lib/BreadcrumbNav.svelte

Add the missing base path to the docs' breadcrumb links (e.g. for github pages).

fix: breadcrumb base path

---

.github/workflows/github-pages.yml

This PR attempts to fix a regression from #590, which causes the `github-pages` workflow to fail because it explicitly uses pnpm 8. This PR changes the workflow to use the same `setup` action as the `ci` workflow.

ci: fix github-pages workflow

---

docs/src/routes/(docs)/components/table-sortable/+page.svelte
icore_open_docs/src/routes/(docs)/components/table-sortable/+page.svelte

Update the icore_open_docs table-sortable page to match the one in the main docs (as updated in #391) and fix the type annotations in both to resolve the CI `check-docs` failure (e.g. [job 27908938797](https://github.com/minvws/nl-rdo-manon/actions/runs/10093373280/job/27908938797)).

chore: update table-sortable in icore_open_docs to match main docs

---

manon/.stylelintrc.json

Disable stylelint's "no-duplicate-selectors" rule, as duplicate selectors are unavoidable with #627.

ci: disable stylelint 'no-duplicate-selectors' rule

---

docs/src/routes/(docs)/components/checkbox/+page.svelte
docs/src/routes/(docs)/components/fieldset-checkbox/+page.svelte
docs/src/routes/(docs)/components/fieldset-radio/+page.svelte
docs/src/routes/(docs)/components/form-input-radio/+page.svelte
icore_open_docs/src/routes/(docs)/components/form-input-radio/+page.svelte

Radio button styling didn't work. The reference to the imports was incorrect in the documentation. I've updated the docs to match the current situation. Also checked the other components for any old references and fixed those. 
Closes: https://github.com/minvws/nl-rdo-manon/issues/622

fix: radio button and checkboxes docs

---

.github/workflows/ci.yml
manon/.stylelintrc.json
manon/package.json
package.json
pnpm-lock.yaml

This PR reverts #638 and adds an `auditConfig` to ignore CVE-2024-4067 (https://github.com/advisories/GHSA-952p-6rrq-rcjv), which is for a vulnerability in `micromatch`, a nested dependency of stylelint. This does not run in production. It does run in CI, but as far as I can tell `stylelint` does not hit `micromatch`'s vulnerable code path (it doesn't call `micromatch.parse` or `micromatch.braces`).
Closes: #637

ci: restore stylelint, ignore micromatch CVE

---

docs/src/routes/(docs)/components/accordion-test/+page.svelte
docs/src/routes/(docs)/components/accordion/+page.svelte
manon/accordion.js

This PR fixes a regression from d5abf55 (discussed in https://github.com/minvws/nl-rdo-manon/pull/574#discussion_r1671578334, released in [v16.3.0-beta.8](https://github.com/minvws/nl-rdo-manon/releases/tag/v16.3.0-beta.8)) which resulted in the first accordion item not being closed-by-default when its button had `aria-expanded="false"` in the initial markup.
I've also elaborated the explanation about this behaviour in the docs and added test cases: 
Fixes: https://github.com/minvws/nl-rdo-manon/pull/574#discussion_r1671578334

fix: accordion explicit `aria-expanded="false"`

---

package.json
pnpm-lock.yaml

Replace the `ignoreCves` from #639 with a pnpm override for micromatch 4.0.8.

fix: update micromatch

---

docs/package.json
examples/vite/package.json
pnpm-lock.yaml

Bump vite from 5.4.1 to 5.4.8. Resolves audit warning for CVE-2024-47068.

fix(deps): bump vite from 5.4.1 to 5.4.8

---

docs/src/routes/(docs)/components/accordion/+page.svelte
docs/src/routes/(docs)/components/link/+page.svelte
docs/src/routes/(docs)/components/navigation/+page.svelte

Closes https://github.com/minvws/nl-rdo-manon/issues/361
I used https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements#list_of_pseudo-elements as a reference and search.replaced all psuedo elements in Manon that I could find.
- :before is now ::before
- :after is now ::after
But I did not change for example :active because it is not a pseudo-element, it is a pseudo-class
I needed to make sure that I did not end up with after a 'search and replace' with something like this: `:::`after` so I did something else first:
- I searched for all existing correct pseudo-elements and swapped the characters.
- I now searched for `:after` and replaced it with `::retfa`
- as a final step I searched for all `::retfa` and replaced them with `::after`
Same method for the `::before` element

fix(docs): writing style pseudo selectors and pseudo elements

---

manon/button-to-top.scss

Meta-PR onto #669. Fixes the squareness and padding on legacy markup for `a.button.to-top.icon`.

fix: button-to-top backwards compatibility

---

docs/src/routes/(docs)/components/table-base/+page.svelte
themes/icore-open/components/table.scss

Fix the `--table-body-head-cell-border-width` of the icore-open theme.
Before|After
------|-----

fix: icore-open table row header border

---

.github/workflows/ci.yml

Fix the CI workflow's trigger events to stop it from running for every push to any branch.

ci: fix ci workflow trigger events

---

.github/actions/setup/action.yml
.github/workflows/ci.yml

Add a separate CI job for npm audit and change the regular pre-install audit's severity level to "high". See #557.

ci: separate npm audit job

---

pnpm-lock.yaml

Update lockfile to bump nanoid from 3.3.7 to 3.3.8 to resolve audit warning.

chore: update lockfile to bump nanoid from 3.3.7 to 3.3.8

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
.github/workflows/github-pages.yml
.github/workflows/publish.yml

- Clean up the workflows and setup action with consistent formatting and names for all jobs and steps.
- Revert to using `setup-node`'s [native pnpm cache](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data) (see also [pnpm docs](https://pnpm.io/continuous-integration#github-actions)).
- Switch runner image to `ubuntu-24.04`.

ci: clean up, use native pnpm cache, switch to ubuntu-24.04

---

.github/dependabot.yml
docs/package.json
pnpm-lock.yaml

Tweak the dependabot groups:
- Rename the "svelte" group to "build" and add `sass` and `vite`. 
- Rename the "prettier" group to "lint" and add `stylelint` and `stylelint-*`.

ci: tweak dependabot groups

---

manon/header-navigation-link-focus-variables.scss
manon/header-navigation-link-focus.scss

Currently with [theme v0.1.0-beta.2](https://github.com/minvws/nl-rdo-rijksoverheid-ui-theme/releases/tag/v0.1.0-beta.2) and [manon v17.0.0-beta.1](https://github.com/minvws/nl-rdo-manon/releases/tag/v17.0.0-beta.1) the current link looks like:
The `Flow` item should look active. 
Chrome Dev tools is showing that the current-link-focus variables are missing, but these variables should not be needed for only the current link styling.
Current link styling should come from here:
https://github.com/minvws/nl-rdo-manon/blob/fa0ae27c478da0f4b4672cae34f68496acdbb995/manon/header-navigation-link-active.scss#L24-L27
Instead from, so I removed the `@extend` line.
https://github.com/minvws/nl-rdo-manon/blob/fa0ae27c478da0f4b4672cae34f68496acdbb995/manon/header-navigation-link-focus.scss#L30-L33
Also …

fix: header navigation current link styles

---

manon/header-navigation-link-focus-variables.scss

Use `navigation-link-focus-*` as fallback for `header-navigation-link-focus-*` to fix header navigation link focus outline styles in themes that do not specify them.

fix: default header-navigation-link-focus-outline

---

package.json

Update pnpm to v10 via the package.json `packageManager` and `engines` fields.
In a future update we'll be able to remove the `engines` field, as starting with pnpm v10 [manage-package-manager-versions](https://pnpm.io/npmrc#manage-package-manager-versions) is on by default, but I've left it for now to warn pnpm 9 users to update.

ci: update pnpm to v10

---

docs/src/scss/iframe.scss

Restore the `iframe` styling from the old [docs.scss](https://github.com/minvws/nl-rdo-manon/blob/b0d9db4/docs/src/scss/docs.scss).

fix: iframe resize

---

docs/src/routes/components/button-dropdown/+page.svelte
docs/src/routes/components/collapsible/+page.svelte

Remove the `aria-label` from [elements that don't support it](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-label#associated_roles) in the example snippets for the `collapsible` and `button-dropdown` components. The documentation did provide any instructions about adding `aria-label`, so the example snippets were the only things that needed to be changed.
Closes #434.

docs: remove incorrect aria-labels from examples

---

.github/workflows/ci.yml
docs/package.json
docs/src/markdown/remark/iframe.js
docs/svelte.config.js
pnpm-lock.yaml

Fix the issue that was causing the [github-pages workflow failures on `main`](https://github.com/minvws/nl-rdo-manon/actions/runs/16726931460) and add a `BASE_PATH` to the CI docs build to make sure it will block future PRs that would break the github pages workflow.

build: correctly rebase iframe src URLs, build docs with BASE_PATH

---

.github/workflows/ci.yml

This PR updates the CI to use the generic sonarqube action.

ci: use generic sonarqube action

---

docs/src/routes/library/components/navigation/+page.md

This PR fixes the closing `<a>` tag issue in the navigation component documentation

fix: issue with `<a>` tag in navigation component documentation

---

manon/components/pagination.scss
manon/variables/_pagination.scss

Fix center alignment of previous and next with pagination.
Fix:

Fix pagination alignment

---

manon/radio.scss

**Related issue:** #358
- Removed dependency on parent `<form>` for `.radio` styling  
- Radios can now be used with or without a wrapper  
```html
<form action="" method="post">
<div class="radio">
<input type="radio" id="radio-example-1" name="example">
<label for="radio-example-1">Option with form wrapper</label>
</div>
</form>
```
```html
<div class="radio">
<input type="radio" id="radio-example-1" name="example">
<label for="radio-example-1">Option with form wrapper</label>
</div>
```

fix: remove required form wrapper from radio inputs (#358)
