docs/documentation/components/form-help-test.html
manon/form-checkbox-variables.scss
manon/form-checkbox.scss
manon/form-horizontal-view-fieldset.scss

- Solves alignment issues for checkboxes within a fieldset within a horizontally aligned form. 
- Added tests to the test page.

Added styling for checkboxes within horizontally aligned fieldsets

---

.github/CODEOWNERS

feat: Added TwistMeister as a codeowner

feat: Added TwistMeister as a codeowner

---

docs/documentation/components/max-line-length.html
docs/documentation/import-styling.html
docs/documentation/variables.html
docs/scss/manon.scss
manon/max-line-length-variables.scss
manon/max-line-length.scss

fix: Updated max line length documentation

fix: Updated max line length documentation

---

manon/application-base-variables.scss
manon/button-base-variables.scss
manon/button-base.scss

Updated: 
- Button state variables (added references)
- Accent color variables (added states)
- Removed accidental code duplication

feat: updated variables

---

manon/nowrap.scss

fix: link line breaks within nowrap elements

fix: link line breaks within nowrap elements

---

docs/documentation/components/application-base.html
docs/documentation/components/branding-colors.html
docs/documentation/components/finn-large.html
docs/documentation/components/finn-medium.html
docs/documentation/components/finn-small.html
docs/documentation/components/spot-large.html
docs/documentation/components/spot-medium.html
docs/documentation/components/spot-mini.html
docs/documentation/components/spot-small.html
docs/documentation/use-css-variable.html

fix: updated css links inside page head where needed

fix: updated css links inside page head where needed

---

docs/documentation/components/paragraph.html

fixed:
- Longer example for better visual representation
- Added variables table

fix: updated paragraph documentation.

---

docs/documentation/components/application-base.html
manon/application-base-variables.scss
manon/form-button-variables.scss
manon/icon-base-variables.scss
manon/skip-to-content-base.scss

- Added documentation for application base. 
- Added variables overview table
- Removed double/unused variables

fix: Added documentation for application base

---

manon/package.json

- Updated release number in package.json

v1.1.0 release

---

docs/documentation/components/form-horizontal-view-test.html
manon/horizontal-view.scss

Updated horizontal view form examples. 
- Divided for readability
- Added examples
- Added side menu
- Added "!important" to horizontal-view to insure the helper class works as expected without any specificity issues. 
To test go to: 
nl-rdo-manon/docs/documentation/components/form-horizontal-view-test.html
Fieldset examples are a todo but can be done in a separate pr.

Divided and updated horizontal view form examples

---

docs/documentation/components/footer.html
manon/footer.scss

fix: Updated footer documentation and styling. Solves the issue where footer text elements don't adhere to footer text color.

fix: Updated footer documentation and styling

---

README.md
docs/static/js/manon.js

feat: Updated readme concerning font license.

feat: Updated readme concerning font license

---

manon/package.json

chore: Updated manon version number

chore: Updated manon version number

---

docs/scss/manon.scss
docs/scss/themes/soft/spot-large.scss
docs/scss/themes/soft/variables.scss

feat: Added branding colors

---

manon/package.json

release test branch v1.1.2

---

manon/package.json

Release v1.1.3

---

docs/documentation/components.html
docs/documentation/components/tag.html
docs/documentation/components/tags.html
docs/scss/manon.scss
manon/application-base-variables.scss
manon/tag-variables.scss
manon/tag.scss
manon/tags-variables.scss
manon/tags.scss
manon/tile.scss

- Added tags element
- Single element tags (.tag) 
- Grouped tags/ one class on a parent (.tags)
Separate pr: 
- Example and test page
- Tags manon branding
Related ticket: 
https://github.com/minvws/nl-rdo-manon/issues/61

feat: Tags component

---

docs/documentation/components/button-base.html
docs/documentation/components/spot-large.html
docs/documentation/variables.html
docs/static/js/manon.js
manon/button-base-variables.scss

- Updated button documentation. Added examples and overview of available variables.

Fix: Added button documentation

---

docs/documentation/components/tag.html
docs/documentation/components/tags-6-3.html
docs/documentation/components/tags-6.html
docs/documentation/components/tags.html
docs/scss/manon.scss
manon/tag-colors-soft.scss
manon/tag-variables.scss
manon/tag.scss
manon/tags-6-3-variables.scss
manon/tags-6-3.scss
manon/tags-6-variables.scss
manon/tags-6.scss
manon/tags.scss

- Added tags documentation, color sets and tests

Added tags documentation

---

manon/package.json

Updated to version number 1.1.4

Updated version number 1.1.4

---

docs/documentation/components/tag.html
docs/documentation/components/tags-6-3.html
docs/documentation/components/tags-6.html

- Added some missing documentation.

Upgraded tags documentation

---

manon/package.json

Updated release number to v.1.1.5

Updated release number

---

docs/documentation/components/tags-6-3.html

fix: Added correct file name in tags-6-3 css example

fix: Added correct file name in tags-6-3 css example

---

manon/package.json

Updated version number to v1.1.6

Updated version number v1.1.6

---

docs/documentation/components.html
docs/documentation/components/application-base.html
docs/documentation/components/font.html
docs/documentation/components/heading-base-set.html
docs/documentation/components/headings.html
manon/headings-base-set-variables.scss
manon/headings-base-set.scss
manon/headings-variables.scss
manon/headings.scss

- Added font documentation. 
- Updated related documentation and styles like headings and heading sets.

Updated fonts documentation

---

docs/scss/main.scss
docs/scss/manon.scss
docs/scss/themes/soft/spot-large.scss
docs/scss/themes/soft/variables.scss
docs/static/js/manon.js

feat: Added theme structure to docs
**Please note** 
This branch will be used as a main branch to add all branding on the separate components.

feat: Added theme structure to docs

---

manon/filter-variables.scss

- Fixed invisible filter text
- Fixed empty variables within filter-variables
Solves: https://github.com/minvws/nl-rdo-manon/issues/82

fixed missing filter text.

---

manon/form-fieldset-variables.scss
manon/headings-variables.scss

Fix: inheritance on component headings.

---

manon/tag-variables.scss
manon/tag.scss

- Linked font size and font-weight correctly.
- Updated default style

fix: tag variables linkage

---

docs/scss/themes/soft/breadcrumb-bar.scss
docs/scss/themes/soft/spot-large.scss
docs/scss/themes/soft/variables.scss
manon/breadcrumb-bar-variables.scss

- Added missing colors to color set
- Included color from the color set to the breadcrumb bar
- Updated breadcrumb-bar-variables file. Filled in empty variables.

Added Manon branding colors and added it to the breadcrumb bar

---

manon/package.json

Updated version number to v2.0.0

Updated version number

---

manon/layout-one-third-two-thirds-variables.scss
manon/layout-two-thirds-one-third-variables.scss

fix: Solves issue where two-thirds-one-third and one-third-two-thirds layout broke.

Added updated layout variable

---

docs/documentation/components/layout-one-third-two-thirds.html
docs/documentation/components/layout-two-thirds-one-third.html
manon/layout-one-third-two-thirds.scss
manon/layout-two-thirds-one-third-variables.scss
manon/layout-two-thirds-one-third.scss

- Updated thirds layout and documentation. 
- Simplified css selector

Updated thirds layout and documentation. Simplified css selector

---

docs/documentation/components/branding-colors.html

fix: alignment issue on branding colors documentation

fix: alignment issue on branding colors documentation

---

docs/documentation/components.html

fix: alignment on components page (Finn was missing indentation)

fix: alignment on components page

---

docs/scss/themes/soft/navigation.scss
docs/scss/themes/soft/variables.scss
manon/navigation-variables.scss
manon/navigation.scss

- Added alignment options
- fix: old linkage issues. (this was an old file, needed updating)
- fix: removed margin on lists within nav so they don't result in unexpected behaviour
- updated manon docs theme to match

fix: upgraded navigation styling options and fixing old linkage issues

---

manon/message-counter-base-variables.scss

- Added content to empty variables so they are available.

fix: message counter linkage

---

docs/documentation/components.html
docs/scss/manon.scss
manon/tabs-variables.scss
manon/tabs.scss

fix: update tabs variables linkage. Added option to have aria current on the li or the link inside the li

fix: update tabs variables linkage. 

---

manon/package.json

Updated version

---

manon/form-help.scss

- Hiding text on the help button
- Removing unneeded margin on the icon
- Fix alignment issues

fix: form help styling

---

manon/colors/notification-colors.scss
manon/notification-base-variables.scss
manon/notification-confirmation-variables.scss
manon/notification-error-variables.scss
manon/notification-explanation-variables.scss
manon/notification-system-message-variables.scss
manon/notification-table-variables.scss
manon/notification-table.scss
manon/notification-warning-variables.scss

Table notification classes

---

manon/filter-variables.scss
manon/filter.scss

- Feat: Added font-weight to filter styling options

Feat: Added font-weight to filter styling options

---

docs/documentation/components/form-inline-test.html
manon/form-inline-variables.scss
manon/form-inline.scss

- Added styling options: 
- gap
- flex-direction
- Added test with multiple objects

feat: Added styling options to inline forms

---

docs/documentation/components/button-container-test.html
docs/documentation/components/button-container.html
docs/documentation/components/button.html
docs/scss/manon.scss
manon/application-base-variables.scss
manon/button-container-variables.scss
manon/button-container.scss

Added button-container styling, documentation and tests

Feat: button-container

---

manon/tile-groups.scss

fix: removing test css

---

manon/tile-image-cover.scss

fix: border-radius on tile cover image

fix: border-radius on tile cover image

---

manon/layout-fifty-fifty.scss

fix: fifty fifty gap

---

docs/documentation/components/de-emphasized.html

- Changed the variables within the overview to the correct name.

fixed variables overview

---

manon/header-navigation-variables.scss

fix: Inherit button padding as default

fix: Inherit button padding as default

---

docs/documentation/components.html
docs/documentation/components/form-base.html
docs/documentation/components/layout-form.html
docs/documentation/components/layouts.html
docs/scss/manon.scss
manon/form-base-variables.scss
manon/form-base.scss
manon/layout-form-variables.scss
manon/layout-form.scss

- Feat: Added layout styling options for forms. 
As requested in:  https://github.com/minvws/nl-covid19-coronacheck-hkvi-web/issues/1799

feat: Added layout form styles

---

docs/documentation/components.html
docs/documentation/components/card.html
docs/scss/manon.scss
manon/card-variables.scss
manon/card.scss

feat: Added card component

---

manon/breadcrumb-bar-variables.scss
manon/breadcrumb-bar.scss

Fix: added whitespace styling option to breadcrumb links

Fix: added whitespace styling option to breadcrumb links

---

docs/documentation/components.html
docs/documentation/components/forms.html
docs/documentation/components/radio-button.html
docs/scss/manon.scss
docs/static/js/manon.js
manon/radio-variables.scss
manon/radio.scss

- feat: radio button component 
- Linter set max line length on manon.js

feat: radio button component

---

docs/documentation/components.html
docs/documentation/components/collapsible-menu.html
docs/static/js/manon.js
manon/button-base.scss
manon/navigation-collapsible-menu-variables.scss
manon/navigation-collapsible-menu.scss
manon/navigation.js

Fix : Collapsible menu documentation (html/css) and styling.

Fix: Collapsible menu documentation and styling

---

docs/static/js/manon.js

fix: one version of manon.js

---

docs/documentation/components.html
manon/navigation-variables.scss
manon/navigation.scss

- Added navigation component styling options.

Added navigation styling

---

manon/footer.scss

Fix: footer styling ul background and before

Fix: footer styling ul background and before

---

docs/static/js/manon.js
manon/footer.scss

- Fix: Solves specificty issue with the color of visited links within navigation elements within the footer

Fix: Icon color within footer on visited links

---

manon/header-navigation-variables.scss
manon/header-navigation.scss

Fix added missing variables

---

manon/icon-base.scss
manon/icon-set-example.scss
manon/language-selector-list.scss

Fix: Removed font-smoothing as it is discontinued and not supported anymore on production sites
Fix: Indentation within manon/language-selector-list.scss

Fix: Removed font-smoothing as it is discontinued

---

docs/static/js/manon.js
manon/package.json

Chore: Updated version number (and js linter build)

Chore: Updated version number

---

manon/header-navigation.scss

Fix: solves specificity issue on header nav visited links

Fix: solves specificity issue on header nav visited links

---

manon/footer.scss

Fix: Fixed specificity footer visited links text color

Fix: Fixed specificity footer visited links text color

---

manon/navigation.scss

Fix: removed double :visited definition

Fix: removed double :visited definition

---

docs/documentation/components/icons-test.html
docs/documentation/components/icons.html
docs/documentation/components/iconset-create.html
manon/breadcrumb-bar-content-block-variables.scss
manon/icon.scss
manon/language-selector-list.scss

Fixes documentation, old variable names and adds language icon test

Fix: Language icon, documentation and adds language icon tests.

---

manon/package.json

Chore: Upgrades version number

Chore: Upgraded version number

---

manon/navigation-collapsible-menu-variables.scss
manon/navigation-collapsible-menu.scss

Fix: Updates uncollapsed menu styling and styling options

Fix: Updates uncollapsed menu styling and styling options

---

manon/breadcrumb-bar-content-block-variables.scss
manon/breadcrumb-bar-content-block.scss

Fixes breadcrumb bar variables

Fix: Breadcrumb bar variables

---

docs/documentation/components/header-example-language-select-list.html
docs/documentation/components/header-example-logo-above.html
docs/documentation/components/header-example-logo.html
docs/documentation/components/header-example-multiple-menus.html
docs/documentation/components/header-example.html
docs/static/css/docs-styling/header/header-example-logo-above-variables.css
docs/static/css/docs-styling/header/header-example-multiple-menus-variables.css
manon/navigation-collapsible-menu-variables.scss
manon/navigation-collapsible-menu.scss

fix: fixes examples
feat: css examples

Fix: Collapsable menu examples

---

docs/documentation/components/language-selector.html
manon/language-selector-list-variables.scss
manon/language-selector-list.scss

Fix: Language selector, added additional styling options changed static values into variable ones.
Moved list description to be the label. To remove an unnecessary double element.

Fix: Language selector, added additional styling options

---

manon/language-selector-list.scss

Replacing a specific fixed value for a more dynamic one.

Fix: Fixes language component width

---

manon/package.json

Chore: Updates version number

---

manon/button-icon-only.scss
manon/button-icon.scss
manon/footer-link.scss
manon/header-navigation-link.scss
manon/icon.scss
manon/link.scss
manon/mixins/icon.scss
manon/navigation-link.scss

Fix: Separates mixins to prevent variable overrides

Fix: Separates mixins to prevent variable overrides

---

manon/footer-variables.scss
manon/footer.scss

- Adds footer nav styling options

Feat: Added styling options for form navigation lists

---

manon/filter-variables.scss
manon/filter.scss

Fix: filter

---

manon/list-base-variables.scss

Fix: List variables

---

docs/scss/themes/soft/header-navigation.scss
manon/header-navigation-variables.scss
manon/header-navigation.scss

Fix: Added header navigation link styling to docs theme

Fix: Added header navigation link styling to docs theme

---

manon/list-base-variables.scss
manon/list-base.scss
manon/sidemenu-base-variables.scss
manon/sidemenu-base.scss

Fix: Fixed missing and incorrect variables

Fix: Fixed missing and incorrect variables

---

manon/icon.scss
manon/sidemenu-base-variables.scss
manon/sidemenu-base.scss

Fix: Added missing icon on closed sidemenu

Fix: Added missing icon on closed sidemenu

---

manon/footer-link-variables.scss
manon/icon-variables.scss
manon/link-variables.scss
manon/link.scss

Use correct variables for example, footerl-link-icon variables should use link-icon variables instead of icon variables.

Update link variables

---

manon/hero.scss

Fix: Fixes unneeded inherited padding on hero.

Fix: Fixes unneeded inherited padding on hero.

---

manon/form-horizontal-view-fieldset.scss

- Fixes missing spacing between grouped fieldset components

Fix: Added missing spacing between grouped fieldset components

---

docs/documentation/components/form-accent-color-test.html
docs/documentation/components/form-base-test.html
docs/documentation/components/form-columns-test.html
docs/documentation/components/form-combined-fields-test.html
docs/documentation/components/form-help-test.html
docs/documentation/components/form-horizontal-view-test.html
docs/documentation/components/form-inline-test.html
docs/documentation/components/form-input-color-filled-test.html
docs/documentation/components/form-input-color-test.html
docs/documentation/components/form-input-date-test.html
docs/documentation/components/form-input-email-test.html
docs/documentation/components/form-input-file-test.html
docs/documentation/components/form-input-password-test.html
docs/documentation/components/form-input-range-test.html
docs/documentation/components/form-input-test.html
docs/documentation/components/form-required-test.html
docs/documentation/components/form-select-test.html

- Fixes breadcrumbs on form test pages

Fix: Breadcrumbs on form test pages

---

manon/form-base.scss
manon/form-button-variables.scss
manon/form-button.scss

- Fix: Inconsistent height between a.button and button within forms
- Chore: Rearranged order of variables for readability

Fix form a.button height

---

docs/documentation/components/notifications-page-example-confirmation.html
docs/documentation/components/notifications-page-example-error.html
docs/documentation/components/notifications-page-example-explanation.html
docs/documentation/components/notifications-page-example-system.html
docs/documentation/components/notifications-page-example-warning.html
docs/documentation/components/notifications-page.html
docs/documentation/components/notifications.html
docs/scss/manon.scss
manon/breadcrumb-bar-content-block-variables.scss
manon/breadcrumb-bar-variables.scss
manon/header-navigation-content-wrapper-variables.scss
manon/header-navigation-variables.scss
manon/layout-set.scss
manon/mixins/notification-type.scss
manon/notification-confirmation-page-variables.scss
manon/notification-confirmation-page.scss
manon/notification-error-page-variables.scss
manon/notification-error-page.scss
manon/notification-explanation-page-variables.scss
manon/notification-explanation-page.scss
manon/notification-system-page-variables.scss
manon/notification-system-page.scss
manon/notification-warning-page-variables.scss
manon/notification-warning-page.scss

- Adds page notifications styling, examples and documentation

Feat: Page notifications

---

docs/documentation/components.html
docs/documentation/components/form-base-test.html
docs/documentation/components/form-notification.html
manon/form-fieldset.scss
manon/form-horizontal-view.scss
manon/notification-block-element-variables.scss
manon/notification-form.scss

- Fix: Documentation form notifications
- Fix: Placement form notifications
- Fix: Notification styling within horizontal forms
- Fix: Notification styling within fieldsets

Fix: Form notifications

---

docs/documentation/components/image-round.html
docs/documentation/components/image-square.html

- Fix: Fixes image shape to be exact square and exact circle
- Adds correct html examples

Fix: Fixes image shape to be exact square and exact circle

---

manon/header-navigation-variables.scss
manon/header-navigation.scss

Feat: Added whitespace

---

manon/form-help-variables.scss
manon/form-help.scss

- Fix: Help button alignment within fieldsets

Fix: Help button alignment within fieldsets

---

docs/documentation/components/notifications-block-element-test.html
docs/documentation/components/notifications-block-element.html
manon/form-horizontal-view-variables.scss
manon/form-horizontal-view.scss

- Fix: Added test and styling fixes for block notifications within forms

Fix: Added test and styling fixes for block notifications within forms

---

manon/image-square-variables.scss
manon/image-square.scss

- Feat: Adds the option to set border-radius on square images

Feat: Adds the option to set border-radius on square images

---

manon/collapsible.scss

Fix: Collapsible css

---

docs/documentation/components/form-horizontal-view-test.html
manon/checkbox-variables.scss
manon/checkbox.scss
manon/form-horizontal-view-fieldset.scss
manon/form-horizontal-view.scss
manon/radio.scss

- Fixes radio button and checkbox alignment

Fix: Radio button and checkbox alignment

---

manon/footer-content-wrapper-variables.scss
manon/footer-content-wrapper.scss

- Feat: Adds footer content wrapper

Feat: Adds footer content wrapper 

---

manon/button-to-top-variables.scss
manon/button-to-top.scss

Feat: Adds icon color styling option on to-top-button

Feat: Adds icon color styling option on to-top-button

---

manon/package.json

Fix: Updated version number to v12.1.0

Fix: Updated version number

---

docs/documentation/components/form-base-test.html
manon/form-horizontal-view.scss

Fix: Link and  button alignment within horizontal forms
- Added tests
- Added styling 
Result:

Fix: Link and  button alignment within horizontal forms

---

manon/article-content-wrapper.scss
manon/div-content-wrapper.scss
manon/footer-content-wrapper.scss
manon/section-content-wrapper.scss

Solves nested padding issues on layout elements

Fix: Nested layout elements behaviour

---

manon/header-navigation-link-variables.scss
manon/header-navigation-link.scss
manon/header-navigation-variables.scss
manon/header-navigation.scss

Fix: Reinstalled navigation link styling.

Fix: Reinstalled navigation link styling.

---

manon/layout-authentication-variables.scss
manon/layout-authentication.scss

Fix: Updates layout-authentication styling. 
- Removes redundant padding.
- Fixes old variables that were missing content.
Breaking change: Removed specific padding styling options on layout-authentication. Remove any related variables if used. The component will use padding received from the default layout components depending on the component that has been used (e.g div, article, section, form)

Fix: Updates layout-authentication styling.

---

manon/max-line-length-variables.scss

Fix: increases max line length to 50rem

Fix: increases max line length to 50rem

---

manon/list-base-variables.scss

Fix: Sets default list padding value to default 40px

Fix: Sets default list padding value to default 40px

---

manon/article-content-wrapper.scss
manon/section-content-wrapper.scss

@HeleenSG maybe we need to add this as a seperate component/ scss file because it is sidemenu related.
But this adds the needed padding when using sidemenu.

Add sidemenu content wrapper styling

---

manon/description-list-variables.scss
manon/description-list.scss

Fix:  dl layout issues

---

manon/filter-variables.scss
manon/filter.scss

Feat: Adds the option to set the width of the filter component

Feat: Adds the option to set the width of the filter component

---

docs/documentation/components/header-example-form-button.html
docs/documentation/components/header-example-multiple-menus.html
docs/scss/manon.scss
manon/button-base-variables.scss
manon/form-inline.scss
manon/header-navigation-button-states-variables.scss
manon/header-navigation-button-states.scss
manon/header-navigation-button-variables.scss
manon/header-navigation-button.scss
manon/header-navigation.scss
manon/header.scss

Add header navigation button

---

docs/scss/manon.scss
manon/button-base-variables.scss
manon/button-base.scss
manon/header-navigation-collapsible-collapsing-element-button-states-variables.scss
manon/header-navigation-collapsible-collapsing-element-button-states.scss
manon/header-navigation-collapsible-collapsing-element-button-variables.scss
manon/header-navigation-collapsible-collapsing-element-button.scss

Also set `--button-base-text-align: center;` by default.

Add header navigation collapsible button styling

---

manon/header-navigation-button-states.scss
manon/header-navigation-button.scss

The styling should be applied to buttons inside the navigation.
This also fixes an issue with the language selector.

Fix header navigation button to be applied on buttons within nav

---

docs/documentation/components/horizontal-center-test.html

Fix: Horizontal center breadcrumbs

Fix: Horizontal center breadcrumbs

---

docs/documentation/components.html
docs/documentation/components/pagination-test.html
docs/documentation/components/pagination.html
docs/scss/manon.scss
manon/pagination-variables.scss
manon/pagination.scss

Adds pagination styling, tests and documentation

Feat: Pagination

---

manon/accordion.scss
manon/layout-authentication.scss
manon/layout-centered.scss
manon/layout-column-2.scss
manon/layout-column-3.scss
manon/layout-column-4.scss
manon/layout-fifty-fifty.scss
manon/layout-form.scss
manon/layout-one-third-two-thirds.scss

Fixes layout when div layout hasn't been added.

Fix: Layout when div layout hasn't been added.

---

manon/header-navigation-collapsible-variables.scss
manon/header-navigation-link-active-variables.scss
manon/header-navigation-link-variables.scss
manon/icon-variables.scss
manon/link-variables.scss
manon/mixins/icon.scss
manon/navigation-link-variables.scss

fix: icon font-size for active links

---

manon/card-variables.scss
manon/card.scss

Fixes card layout. Adds styling option for width.

Fix: Card layout

---

manon/max-line-length.scss

Added headers to max line length

Fix: Added headers to max line length

---

docs/documentation/components.html
docs/documentation/components/button-dropdown.html
docs/documentation/components/tabs-test.html
docs/documentation/components/tabs.html
manon/tabs.scss

Added tabs documentation

---

README.md

While looking for the ‘why the current solutions weren’t suitable’ docs I encountered a few typos which I fixed.

Minor typos fixed

---

docs/documentation/components/button-destructive-test.html
docs/documentation/components/button-destructive.html
docs/documentation/components/button.html
docs/scss/manon.scss
manon/button-destructive-variables.scss
manon/button-destructive.scss

Added button type for destructive buttons.

Feat added destructive button

---

docs/documentation/components/tabs.html

Updates tabs documentation

---

docs/documentation/components/tabs.html
manon/tabs-variables.scss
manon/tabs.scss

Fixes styling issues with tabs where top and bottom borders on items were not working as they should.

fix: tabs styling

---

manon/tabs-variables.scss
manon/tabs.scss

Fixes tabs border

---

docs/documentation/components/tabs.html
manon/tabs-variables.scss
manon/tabs.scss

- Adds the option to style tabs font weight
- Updates tabs docs

Fixes tabs styling

---

docs/documentation/components/description-list.html
manon/description-list-variables.scss
manon/description-list.scss

Fix: Updates description list styling and documentation
- Adds the ability to set the flex-direction before and after breakpoint
- More styling options to set the width of the elements
- Added styling options for the elements
- Fixes dl div width issue within forms

Fix: Updates description list styling and documentation

---

manon/description-list-variables.scss

Fix: Adds missing dl variables

Fix: Adds missing dl variables

---

docs/documentation/components/description-list.html

Adds test case to description list documentation

dl documentation update

---

manon/description-list.scss

fix(description-list): correct styling dl in form fieldset

---

manon/card.scss

fix(card-gap): fix card gap on breakpoint values

---

docs/documentation/components/logo.html

Updated logo example for improved accessibility.

Updated logo example

---

docs/documentation/components/table-expando-row.html
manon/navigation.js

Updates old classname within documentation to current one

Fix: Updates documentation for expando rows

---

.github/workflows/github-pages.yml
docs/src/lib/SiteNav.svelte
docs/src/lib/SiteNavLinks.svelte
docs/src/routes/(docs)/+page.svelte
docs/src/routes/(docs)/components/header-navigation/example-content-wrapper/+page@.svelte
docs/src/routes/(docs)/components/header-navigation/example-form-button/+page@.svelte
docs/src/routes/(docs)/components/header-navigation/example-language-select-list/+page@.svelte
docs/src/routes/(docs)/components/header-navigation/example-logo-above/+page@.svelte
docs/src/routes/(docs)/components/header-navigation/example-logo/+page@.svelte
docs/src/routes/(docs)/components/header-navigation/example-multiple-menus/+page@.svelte
docs/src/routes/(docs)/components/sidemenu/in-page-collapsible/+page.svelte
docs/src/routes/(docs)/components/sidemenu/in-page/+page.svelte
docs/src/routes/(docs)/components/sidemenu/next-to-page-collapsible/+page@.svelte
docs/src/routes/(docs)/components/sidemenu/next-to-page/+page@.svelte
docs/svelte.config.js

fix(docs): github pages base path

---

manon/background-color-offset-variables.scss
manon/background-color-offset.scss
themes/soft/components/background-color-offset.scss
themes/soft/theme.scss

This reverts PR #414 (commit 6f00beb3393a4b9cce626a1bb5c4fbb732f4062e), which inadvertently introduced a breaking change.

revert: Adds styling options for background-color-offset component (#414)

---

docs/src/redirects.js

Add a few more redirects for known-known URLs.

docs: add missing redirects

---

docs/src/routes/(docs)/components/accordion-test/+page.svelte
docs/src/routes/(docs)/components/accordion/+page.svelte
docs/src/routes/(docs)/components/checkbox-test/+page.svelte
docs/src/routes/(docs)/components/fieldset-checkbox-test/+page.svelte
docs/src/routes/(docs)/components/form-input-range-test/+page.svelte
docs/src/routes/(docs)/components/form-input-range/+page.svelte
docs/src/routes/(docs)/components/form-select-test/+page.svelte
docs/src/routes/(docs)/documentation/variables/+page.svelte

This PR fixes some of the duplicate `id`s in the docs. The rest of them will be fixed by #534.

docs: fix duplicate ids

---

themes/basic-bold/components/button-ghost.scss
themes/basic-bold/theme.scss
themes/soft/components/button-ghost.scss
themes/soft/theme.scss

Increases ghost button contrast to be above the required 4.5.
Solves: https://github.com/minvws/nl-rdo-manon/issues/424

fix: ghost button contrast

---

docs/src/scss/main.scss
manon/pagination-variables.scss
manon/pagination.scss
themes/basic-bold/components/pagination.scss
themes/basic-bold/fundamentals/colors.scss
themes/basic-bold/theme.scss

Fixes pagination active state contrast. 
Solves: https://github.com/minvws/nl-rdo-manon/issues/428

fix: pagination active state contrast

---

icore_open_docs/src/routes/(docs)/components/+page.svelte
themes/icore-open/components/link.scss
themes/icore-open/theme.scss

- Adds links docs page
- Adds link styling

feat: Adds link styling and docs to iCore open theme

---

docs/src/routes/(docs)/components/notifications-page-example-confirmation/+page.svelte
icore_open_docs/src/routes/(docs)/components/notifications-page-example-confirmation/+page.svelte

fix: Updates notification documentation.

---

themes/icore-open/components/form-input.scss
themes/icore-open/components/radio-input.scss

fix: Adds missing references to color scheme

fix: Adds missing references to color scheme

---

icore_open_docs/src/routes/(docs)/components/button/+page.svelte
icore_open_docs/src/scss/manon-components.scss
manon/button-cta-variables.scss
themes/icore-open/components/button-cta.scss
themes/icore-open/theme.scss

- Adds button cta to icore open theme

feat: Adds button cta to icore open theme

---

icore_open_docs/src/routes/(docs)/components/header-navigation/example-form-button/+page@.svelte
themes/icore-open/theme-specific-components/avatar.scss
themes/icore-open/theme-specific-components/header-navigation-actions.scss
themes/icore-open/theme.scss

- Adds avatar to iCore theme.
- Adds avatar to header example.

feat: iCore theme avatar

---

icore_open_docs/src/routes/(docs)/components/button-call-to-action/+page.svelte

fix: updates cta button documentation iCore theme

---

themes/icore-open/fonts/fonts.scss

In iCore theme: 
- Adds bold font reference
- Sets body text set

fix: Adds bold font reference

---

icore_open_docs/src/scss/manon-components.scss
manon/footer-navigation-link-focus-variables.scss
manon/footer-navigation-link-focus.scss
manon/header-navigation-link-focus-variables.scss
manon/header-navigation-link-focus.scss
manon/header-navigation-link-visited.scss
manon/link-visited-variables.scss
manon/link-visited.scss
manon/mixins/outline.scss
themes/icore-open/components/footer-navigation-link-focus.scss
themes/icore-open/components/footer-navigation-link-visited-hover.scss
themes/icore-open/components/footer-navigation-link-visited.scss
themes/icore-open/components/header-navigation-link-active.scss
themes/icore-open/components/header-navigation-link-focus.scss
themes/icore-open/components/header-navigation-link-hover.scss
themes/icore-open/components/header-navigation-link-visited.scss
themes/icore-open/components/header-navigation.scss
themes/icore-open/components/link-active.scss
themes/icore-open/components/link-hover.scss
themes/icore-open/components/link-visited.scss
themes/icore-open/theme.scss

- Adds missing states to icore open theme
- Adds additional styling options to link state styling in Manon

fix: Adds link state styling iCore open theme

---

manon/breadcrumb-bar.scss
manon/button-icon-only.scss
manon/button-icon.scss
manon/collapsible.scss
manon/header-navigation-button.scss
manon/header-navigation-collapsible-collapsing-element-button.scss
manon/header-navigation-link.scss
manon/link-external.scss
manon/mixins/icon.scss
manon/mixins/layout.scss
manon/mixins/link.scss
manon/mixins/notification-type.scss
manon/mixins/outline.scss
manon/notification.scss
manon/pagination.scss
manon/sidemenu.scss

Updates scss to align with how native css behaves. 
For more information see: https://sass-lang.com/documentation/breaking-changes/mixed-decls/

fix: Opt into native css nesting behaviour

---

manon/hero-variables.scss

Fixes hero overflow issue where content runs out of the hero element.

fix: hero overflow issue

---

.reuse/dep5
LICENSE.md
README.md
REUSE.toml
manon/package.json
themes/package.json

chore: use REUSE 3.2

---

manon/logo.scss

&nbsp;|No focus|With focus (Firefox)|With focus (Chrome)
--|--|--|--
Before|![Screenshot_20250211_095211](https://github.com/user-attachments/assets/c8ccd154-fc93-4ff3-a20c-026a64332033)|![Screenshot_20250211_095221](https://github.com/user-attachments/assets/21505dc3-8e20-4e4b-bf23-f94917bfcab3)|![Screenshot_20250211_095237](https://github.com/user-attachments/assets/6dfa68eb-7cc2-42bf-ae8b-8c4befed8d7e)
After|![Screenshot_20250211_113914](https://github.com/user-attachments/assets/5cda973e-101a-4aab-b921-eaf7cb7f35fa)|![Screenshot_20250211_113921](https://github.com/user-attachments/assets/95ffe3e9-5b4a-4ca6-8856-da9ccd5eac0c)|![Screenshot_20250211_114051](https://github.com/user-attachments/assets/1f147c78-7772-4bb7-b749-11775f607441)

fix: logo focus image alignment and text visibility

---

manon/navigation.scss

Set display fallback to initial

fix: set navigation-list-item-icon-display fallback to initial

---

docs/src/routes/components/header-navigation/+page.svelte

This PR updates and adds the necessary header-navigation components.

docs: add the necessary header-navigation components

---

docs/src/scss/main.scss
manon/components/button-container.scss
manon/omzetten/button-container.scss
manon/variables/_button-container.scss
manon/variables/_index.scss

Base branch: [feat/manon-sass](https://github.com/minvws/nl-rdo-manon/tree/feat/manon-sass)
Theme variables are initiated with `apply-from-theme() function`. All variables that are defined in this function can be replaced by setting theme variables, the defaut is `null !default;`

Refactor button container

---

docs/src/scss/main.scss
manon/components/de-emphasized.scss
manon/variables/_de-emphasized.scss
manon/variables/_index.scss

Base branch: [feat/manon-sass](https://github.com/minvws/nl-rdo-manon/tree/feat/manon-sass)
Theme variables are initiated with `apply-from-theme() function`. All variables that are defined in this function can be replaced by setting theme variables, the defaut is `null !default;`

Refactor de-empasized

---

manon/components/checkbox.scss
manon/components/footer-two-thirds-one-third.scss

Changes the way we define the `styles` map up front. Making it more concise.

Make not-null checks more concise

---

themes/icore-open/_index.scss

Removes padding: 0 as it introduces alignment issues.

Fix: iCore Open list styling

---

themes/icore-open/_index.scss

Adds button background color to icore open theme

Adds button background color to icore open theme

---

manon/notification-variables.scss
manon/notification.scss

adds the option to style max width on notifications within themes

feat: Notification max width

---

manon/hero-variables.scss
manon/hero.scss
manon/sidemenu-variables.scss
manon/sidemenu.scss

- Adds styling options for layout settings within pages with a sidemenu and pages with a hero section.

fix: Layout options

---

.github/workflows/publish.yml
manon/package.json
themes/README.md
themes/package.json

Closes https://github.com/minvws/nl-rdo-manon/issues/659
Will add sections "Customizing Themes", "Create your own themes" and "Testing your theme" to the `manon-themes` readme for the `manon-sass` branch.

chore: add package readme's

---

docs/src/routes/examples/pages/basic/+page@.svelte

fixes example page header position

fix: Example pages header position

---

docs/src/routes/library/components/accordion/+page.md
manon/components/accordion.scss
manon/variables/_accordion.scss
themes/icore-open/_index.scss

- Adds Accordion styling to iCore Open theme
- Adds accordion styling options
- Simplifies examples
- Corrects button font-size variable name.

feat: Accordion iCore Open theme styling

---

manon/components/article-section.scss
manon/components/article.scss
manon/components/div.scss
manon/components/footer.scss
manon/components/hero.scss
manon/components/section.scss
manon/variables/_div.scss

Fixes header layout in icore theme. And prevents unwanted changes due to flex-direction being set.

fix: div default behaviour

---

docs/src/routes/+page.svelte

A naive implementation of referencing older version of the docs.

feat: add documentation version links

---

manon/components/article.scss
manon/components/section.scss

Fix article styling

---

docs/src/routes/+page.svelte
docs/src/routes/getting-started/tutorial/+page.md

- Updates tutorial
- Updates homepage (reference to tutorial)

fix: update tutorial
